from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


# ============ Form Schema Models (for LLM output) ============

class FormQuestion(BaseModel):
    """Represents a single question in a Google Form"""
    title: str = Field(..., description="The question text")
    question_type: str = Field(..., description="Question type: TEXT, MULTIPLE_CHOICE, or CHECKBOX")
    options: Optional[List[str]] = Field(None, description="Options for MULTIPLE_CHOICE or CHECKBOX questions")
    required: bool = Field(True, description="Whether the question is required")


class FormSchema(BaseModel):
    """Complete form schema generated by LLM"""
    title: str = Field(..., description="Form title")
    description: str = Field(..., description="Form description")
    questions: List[FormQuestion] = Field(..., description="List of questions")


# ============ API Request/Response Models ============

class FormGenerationRequest(BaseModel):
    """Request model for form generation endpoint"""
    prompt: str = Field(..., min_length=1, description="Natural language prompt describing the form")


class FormGenerationResponse(BaseModel):
    """Response model for form generation endpoint"""
    form_url: str = Field(..., description="URL to the generated Google Form")
    form_id: str = Field(..., description="Google Form ID")
    title: str = Field(..., description="Form title")
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ============ MongoDB Document Models ============

class UserSession(BaseModel):
    """User session stored in MongoDB"""
    session_id: str
    user_email: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: datetime


class OAuthToken(BaseModel):
    """OAuth token stored in MongoDB (encrypted)"""
    user_email: str
    access_token: str  # Will be encrypted
    refresh_token: str  # Will be encrypted
    token_expiry: datetime
    created_at: datetime = Field(default_factory=datetime.utcnow)


class FormHistory(BaseModel):
    """Form generation history stored in MongoDB"""
    user_email: str
    form_id: str
    form_url: str
    form_title: str
    prompt: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
